FROM apache/nifi:1.9.2

ENV NIFI_FLOW_CONFIGURATION_FOLDER="${NIFI_HOME}/flow_conf"
ENV NIFI_FLOW_CONFIGURATION_FILE="${NIFI_FLOW_CONFIGURATION_FOLDER}/flow.xml.gz"
ENV NIFI_FLOW_CONFIGURATION_ARCHIVE_DIR="${NIFI_FLOW_CONFIGURATION_FOLDER}/archive/"
ENV NIFI_FLOWSERVICE_WRITEDELAY_INTERVAL="2 sec"

USER root

ADD sh/ ${NIFI_BASE_DIR}/scripts/

RUN chown -R nifi:nifi ${NIFI_BASE_DIR} \
    && mkdir -p ${NIFI_FLOW_CONFIGURATION_FOLDER} \
    && chmod +x ${NIFI_BASE_DIR}/scripts/*.sh

USER nifi

VOLUME ${NIFI_FLOW_CONFIGURATION_FOLDER}