name: Docker Image CI

on:
  pull_request:
    branches:
    - develop
  push:
    branches:
    - master
    - develop
    - release/*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jmtvms/docker-developer-nifi:${{ github.ref }}
